name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🚧 Set up project
        run: yarn dev:prepare

      - name: 🛠 Build project
        run: yarn build

      - name: 🧪 Test project
        run: yarn lint && yarn types
#        run: yarn test -- --coverage

#      - name: 🟩 Coverage
#        uses: codecov/codecov-action@v3
